version: "3"
services:
  db:
     build:
       context: ./Docker/
       dockerfile: Dockerfile.mongod
     volumes:
       - data:/data/db
     networks:
       - shouldinetwork
  app:
      build:
        context: ./Docker/
        dockerfile: Dockerfile.flask
      depends_on:
        - db
      networks:
        - shouldinetwork
  web:
      build:
        context: ./Docker/
        dockerfile: Dockerfile.nginx
      depends_on:
        - app 
      ports: 
        - "80:8080"
      networks:
        - shouldinetwork

volumes:
  data:
networks:
  shouldinetwork:
    driver: bridge
