FROM python:3.7
RUN apt-get update -y &&  apt-get install
RUN apt-get install vim -y
RUN pip install --upgrade pip
RUN mkdir /shouldipickitup
COPY . /shouldipickitup
WORKDIR /shouldipickitup
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["/usr/local/bin/gunicorn", "-w 4", "app:app", "--access-logfile access.log" ]
