version: "3"
services:
  db:
     build:
       context: .
       dockerfile: ./Docker/Dockerfile.mongod
     volumes:
       - data:/data/db
     networks:
       - shouldinetwork
     logging:
        driver: awslogs
        options:
          awslogs-region: us-west-2
          awslogs-group: mongodb 
  app:
      build:
        context: .
        dockerfile: ./Docker/Dockerfile.flask
      depends_on:
        - db
      networks:
        - shouldinetwork
      logging:
        driver: awslogs
        options:
          awslogs-region: us-west-2
          awslogs-group: flask 
  web:
      build:
        context: .
        dockerfile: ./Docker/Dockerfile.nginx
      depends_on:
        - app 
      ports: 
        - "80:8080"
      networks:
        - shouldinetwork
      logging:
        driver: awslogs
        options:
          awslogs-region: us-west-2
          awslogs-group: nginx 

volumes:
  data:
networks:
  shouldinetwork:
    driver: bridge
