FROM python:3.7

RUN apt-get update  -y && \ 
    apt-get install -y --no-install-recommends vim \
    curl \
    net-tools \
    telnet && pip install --upgrade pip

RUN mkdir /shouldipickitup/ 
WORKDIR /shouldipickitup/

COPY requirements.txt /shouldipickitup/
RUN pip install -r requirements.txt

RUN mkdir /shouldipickitup/non-app/    && chown -R nobody:  /shouldipickitup/non-app/
RUN mkdir /shouldipickitup/static/     && chown -R nobody:  /shouldipickitup/static/ 
RUN mkdir /shouldipickitup/templates/  && chown -R nobody:  /shouldipickitup/templates/ 
RUN mkdir /shouldipickitup/lib/
RUN mkdir /shouldipickitup/data/

COPY static/    /shouldipickitup/static/
COPY non-app/   /shouldipickitup/non-app/
COPY templates/ /shouldipickitup/templates/
COPY data/      /shouldipickitup/data/
COPY main.py    /shouldipickitup/
COPY app.py     /shouldipickitup/
COPY lib/       /shouldipickitup/lib/

RUN chown -R nobody:  /shouldipickitup/

COPY Docker/flask-docker-entrypoint.sh /usr/sbin/
RUN chmod 755 /usr/sbin/flask-docker-entrypoint.sh 

USER nobody
ENTRYPOINT ["/usr/sbin/flask-docker-entrypoint.sh"]
EXPOSE 8000
