version: "3"
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile.flask
      networks:
        - shouldinetwork
      logging:
        driver: awslogs
        options:
          awslogs-region: $AWS_REGION 
          awslogs-group: flask 
  web:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      depends_on:
        - app 
      ports: 
        - "80:8080"
      networks:
        - shouldinetwork
      logging:
        driver: awslogs
        options:
          awslogs-region: $AWS_REGION 
          awslogs-group: nginx 
networks:
  shouldinetwork:
    driver: bridge
